# setup environment
dist: xenial 
sudo: required
language: csharp
mono: none
# setup container matrix
matrix:
  include:
    - env: OS='ubuntu:16.04'
    - env: OS='centos:7'
    - env: OS='debian:9.7'

before_install:
  - docker pull $OS

script:
  - docker run $OS /bin/sh -c "sudo apt-get install curl; curl -o- https://dot.net/v1/dotnet-install.sh | bash; dotnet restore 'test/GdalCoreTest/GdalCoreTest.csproj'; dotnet run --project 'test/GdalCoreTest/GdalCoreTest.csproj'"
